### ISSUE TITLE
ENH YAML config file with dictionaries 

### ISSUE THREAD

**Issue by rflamary** [benchopt/benchopt#704]
It would be very interesting to have config files in YAML that can handle both inline  parameter  `MNIST[n_sample=100]` (AKA command line) but also dictionary set.

An example of something that would be nice:
```yaml
objective:
  - Awesome benchmak
dataset:
  - MNIST
      n_samples: [100, 500, 1000]
solver:
  - SVC
  - XGBOOST
n-repetitions: 5

```
because it is muchh more readable/editable than the line `MNIST[n_samples=[100, 500, 1000]]` and allows for more paralmeters to be set.

This woudl also be nery jice to handle when a parameter is a dictionary

```yaml
objective:
  - Awesome benchmak
dataset:
  - MNIST
      myparam: 
        n_sample: 10
        normalize: True
solver:
  - SVC
  - XGBOOST
n-repetitions: 5
```
